describe('Helsinki city bike web app', function () {
  it('front page can be opened', function () {
    cy.visit('')
    cy.contains('Helsinki City Bike app')
  })
  it('stations page can be opened', function () {
    cy.visit('')
    cy.get('#stations').click()
    cy.contains('Stations')
    cy.contains('Station name')
    cy.contains('Address')
    cy.contains('Station ID')
  })
  it('search station', function () {
    cy.visit('')
    cy.get('#stations').click()
    cy.get('#search').type('keilalahti')
    cy.get('.row').eq(0).should('contain', 'Keilalahti')
    cy.get('#search').clear()
    cy.get('#search').type('golfpolku')
    cy.get('.row').eq(0).should('contain', 'Golfpolku')
  })
  it('specific station information can be opened', function () {
    cy.visit('')
    cy.get('#stations').click()
    cy.contains('Hanasaari').click()
    cy.contains('Hanasaari station information')
    cy.contains('Address')
    cy.contains('Hanasaarenranta 1')
    cy.contains('Station ID')
    cy.contains('501')
  })
  it('specific station information can be opened after search', function () {
    cy.visit('')
    cy.get('#stations').click()
    cy.get('#search').type('keilalahti')
    cy.get('.row').eq(0).should('contain', 'Keilalahti')
    cy.contains('Keilalahti').click()
    cy.contains('Keilalahti station information')
    cy.contains('Address')
    cy.contains('Keilalahdentie 2')
    cy.contains('Station ID')
    cy.contains('503')
  })
  it('journeys page can be opened', function () {
    cy.visit('')
    cy.get('#journeys').click()
    cy.contains('Journeys')
    cy.contains('Departure station id')
    cy.contains('Departure station name')
    cy.contains('Return station name')
    cy.contains('Covered distance (km)')
    cy.contains('Duration (min)')
  })
  it('journeys are sorted by asc, desc and clear sorting', function () {
    cy.visit('')
    cy.get('#journeys').click().wait(3000)
    cy.contains('Departure station id').click().wait(3000)
    cy.contains('9')
    cy.contains('Erottajan aukio')
    cy.contains('Departure station id').click().wait(3000)
    cy.contains('625')
    cy.contains('Suomenlahdentie')
    cy.contains('Hanasaari')
  })
  it('search journey', function () {
    cy.visit('')
    cy.get('#journeys').click().wait(3000)
    cy.get('#search').type('keilalahti')
    cy.get('.row').eq(0).should('contain', 'Keilalahti')
    cy.get('#search').clear()
    cy.get('#search').type('hanasaari')
    cy.get('.row').eq(0).should('contain', 'Hanasaari')
  })
})
